name: Deploy to VPS

on:
  push:
    branches:
      - main # Or your main development branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_KEY: ${{ secrets.VPS_PRIVATE_KEY }}   # Recommended: Set this secret

        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ env.VPS_KEY }}
          port: 22 # Or your SSH port
          script: |
            echo "Pulling latest changes..."
            cd /hyvve-backend/
            git pull origin main

            echo "Stopping and removing old containers..."
            sudo docker compose down

            echo "Building new image and starting containers..."
            sudo docker compose up --build -d

            echo "Deployment successful!"